### ISSUE TITLE
Paired punctuation

### ISSUE THREAD

**Issue by bulbulistan** [UniversalDependencies/UD_Maltese-MUDT#1]
From the guidelines:
`Paired punctuation marks (e.g. quotes and brackets, sometimes also dashes, commas and other) should be attached to the same word unless that would create non-projectivity.`
And what if it does create non-projectivity as in the example below?
![immagine](https://user-images.githubusercontent.com/18728008/56866850-79e1ad00-69de-11e9-8dfe-61632672d7bb.png)

**Comment by jnivre** [comment]
The projectivity constraint has higher priority, so in this case the second quotation mark has to be attached to the adjective.

**Comment by bulbulistan** [comment]
Thank you @jnivre.
